format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$nodejs\
$golang\
$aws\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[directory]
read_only = " "
truncation_length = 4
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[aws]
disabled = true
