gui:
    sidePanelWidth: 0.2 # gives you more space to show things side-by-side
    skipDiscardChangeWarning: true
git:
    paging:
        colorArg: never
        pager: delta --dark --paging=never
os:
  editPreset: 'nvim'
